### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Teezton** [Humberd/GiveawayAutoEnterer-IndieGala#2]
[Not](https://imgur.com/p9RSRpX) working.
[Errors](https://imgur.com/PfO3bYK) on console.

**Comment by Humberd** [comment]
Thank you, i'll take a look

**Comment by Humberd** [comment]
This kind of bugs happen, when someone on IndieGala dev team changes some html selectors.

**Comment by Teezton** [comment]
Working again, thank you!

> I am not going to touch this script anytime soon, unless entering giveaways will have been broken.

Do you fixed this time?
